### ISSUE TITLE
by="AppIB" doesn't exist

### ISSUE THREAD

**Issue by 2uanta** [tascor/appleStoreScraper#2]
I am reviewing your sample code prior to the MTL R Meetup.
I am not able to run the STEP 4: MERGE THE TWO FILES 
as described in the README:

  apple_top_app <-merge(top_apps_charts_books_data,apple_data,all.x=T,by="AppID"

The problem is that AppID is not a known column in ether of these tables. Should I use another column?

**Comment by jpmallette** [comment]
Hi Quan, 

Thanks for review ! it's so nice ! first comment ! 

I just added how to extract appID in the readme ! It should work now ! 

Cheers and see you tomorrow ! 

Jp
