### ISSUE TITLE
"sampleAnalysis.R"

### ISSUE THREAD

**Issue by 2uanta** [tascor/appleStoreScraper#3]
Hi Jean-Philippe,

Thanks for the new README. I am able to run the code now.
One other details, you mentioned about the file "sampleAnalysis.R" but it's not in the list in the repo?

Quan,

**Comment by jpmallette** [comment]
hi Quan,

Yeah, I have decided to remove the file from the repo. I will delete this in the readme. You can see code sample for analysis at the end of the r meetup.r

Jp,
